### ISSUE TITLE
Bug: Nil value when indexing popoutButton,,,

### ISSUE THREAD

**Issue by nancikennedy** [itsSinba/GearFlyout#3]
On Retail, after updating to v1.11 an error is happening when closing the paperdoll. I rolled back to 1.10 and it went away.

15x Blizzard_FrameXML/EquipmentFlyout.lua:604: attempt to index field 'popoutButton' (a nil value)
[string "@Blizzard_FrameXML/EquipmentFlyout.lua"]:604: in function `EquipmentFlyoutPopoutButton_HideAll'
[string "@Blizzard_UIPanels_Game/Mainline/PaperDollFrame.lua"]:2368: in function <...s/Blizzard_UIPanels_Game/Mainline/PaperDollFrame.lua:2367>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:442: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:473: in function `MoveUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:516: in function `HideUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:169: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:161>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:789: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:772>
[string "=[C]"]: ?
[string "=[C]"]: in function `HideUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:959: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:946>
[string "=[C]"]: in function `CloseWindows'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:994: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:992>
[string "=[C]"]: in function `securecall'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:2815: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
flyout = EquipmentFlyoutFrame {
 0 = <userdata>
 Highlight = EquipmentFlyoutFrameHighlight {
 }
 buttons = <table> {
 }
 button = Button {
 }
 NavigationFrame = Frame {
 }
 totalItems = 1
 buttonFrame = EquipmentFlyoutFrameButtons {
 }
 numItemButtons = 1
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'popoutButton' (a nil value)"
popoutButtons = <table> {
 1 = CharacterHeadSlotPopoutButton {
 }
 2 = CharacterNeckSlotPopoutButton {
 }
 3 = CharacterShoulderSlotPopoutButton {
 }
 4 = CharacterBackSlotPopoutButton {
 }
 5 = CharacterChestSlotPopoutButton {
 }
 6 = CharacterShirtSlotPopoutButton {
 }
 7 = CharacterTabardSlotPopoutButton {
 }
 8 = CharacterWristSlotPopoutButton {
 }
 9 = CharacterHandsSlotPopoutButton {
 }
 10 = CharacterWaistSlotPopoutButton {
 }
 11 = CharacterLegsSlotPopoutButton {
 }
 12 = CharacterFeetSlotPopoutButton {
 }
 13 = CharacterFinger0SlotPopoutButton {
 }
 14 = CharacterFinger1SlotPopoutButton {
 }
 15 = CharacterTrinket0SlotPopoutButton {
 }
 16 = CharacterTrinket1SlotPopoutButton {
 }
 17 = CharacterMainHandSlotPopoutButton {
 }
 18 = CharacterSecondaryHandSlotPopoutButton {
 }
}

**Comment by itsSinba** [comment]
thanks for reporting it. it's odd, I can't seem to reproduce it. does it right away after loading ? if not, can you give me more details on how/when it happens ?

**Comment by nancikennedy** [comment]
It happens when I switch from the sets tab to the stats tab

**Comment by itsSinba** [comment]
I can't really put my finger on it but it seems like another addon is interfering with mine. I'll change methods of handling the buttons on the next update (1.12), should clear any conflicting issues

**Comment by itsSinba** [comment]
pushed 1.12, let me know if you encounter the same issue
